version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: datascience_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - data-network

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - data-network
    depends_on:
      - postgres

  jupyter:
    build: .
    container_name: jupyter_container
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/home/jovyan/data
    networks:
      - data-network
    depends_on:
      - postgres

networks:
  data-network:

volumes:
  postgres_data:
  pgadmin_data:
